api/urls.py
from django.conf.urls import url
from .views import PostListAPIView, PostDetailAPIView, PostCreateAPIView, PostDeleteAPIView, PostUpdateAPIView

urlpatterns = [
	url(r'^list/$', PostListAPIView.as_view(), name="list"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^detail/(?P<post_slug>[-\w]+)', PostDetailAPIView.as_view(), name="detail"),
	url(r'^delete/(?P<post_slug>[-\w]+)', PostDeleteAPIView.as_view(), name="delete"),
	url(r'^update/(?P<post_slug>[-\w]+)', PostUpdateAPIView.as_view(), name="update"),
	
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace="posts")),
    url(r'^api/', include('api.urls', namespace="api")),
    #url(r'^posts/$', views.post_home, name="posts")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^list/$', views.post_list, name="list"),
	url(r'^create/$', views.post_create, name="create"),
	url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name="detail"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name="update"),
	url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name="delete"),
]


#url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name="detail"),

api/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=30)
	content = models.TextField()
	image = models.ImageField(null=True, blank=True, upload_to="post_images")
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(unique=True)

	class Meta:
		ordering = ["-timestamp", "-updated"]


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"post_slug": self.slug})



def create_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(instance.title)
		qs = Post.objects.filter(slug=slug)
		exists = qs.exists()
		if exists:
			slug = "%s-%s"%(slug, instance.id)
		instance.slug = slug
		instance.save()

post_save.connect(create_slug, sender=Post)


	# def create_slug(instance, new_slug=None):
	# 	slug = slugify(instance.title)
	# 	if slug is not None:
	# 		slug = new_slug
	# 	exists = Post.objects.filter(slug=slug).exists()
	# 	if exists:
	# 		new_slug = "%s-%s"%(slug, instance.id)
	# 		return create_slug(instance, new_slug=new_slug)
	# 	return slug

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'image']

api/views.py
from django.shortcuts import render
from rest_framework.generics import ListAPIView, RetrieveAPIView, DestroyAPIView, CreateAPIView, RetrieveUpdateAPIView
from posts.models import Post
from .serializers import PostListSerializer, PostDetailSerializer, PostDeleteSerializer, PostCreateSerializer, PostUpdateSerializer

# Create your views here.
class PostListAPIView(ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostListSerializer
	lookup_field = 'slug'
	lookup_url_kwarg = 'post_slug'

class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	lookup_url_kwarg = 'post_slug'


class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateSerializer
	lookup_field = 'slug'
	lookup_url_kwarg = 'post_slug'

class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDeleteSerializer
	lookup_field = 'slug'
	lookup_url_kwarg = 'post_slug'

class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostUpdateSerializer
	lookup_field = 'slug'
	lookup_url_kwarg = 'post_slug'	

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def post_list(request):
	object_list = Post.objects.all()
	paginator = Paginator(object_list, 10)
	page = request.GET.get('page')
	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		objects = paginator.page(1)
	except EmptyPage:
		objects = paginator.page(paginator.num_pages)

	context = {
		"post_list": objects,
		"title": "List",
	}
	return render(request, "post_list.html", context)


def post_detail(request, post_slug):
	object_detail = get_object_or_404(Post, slug=post_slug)
	context = {
		"title": "Detail",
		"object_detail": object_detail,
	}
	return render(request, "post_detail.html", context)

def post_create(request):
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		form.save()
		messages.success(request, "Sucessfully created!")
		return redirect("posts:list")
	context = {
		"title": "Create",
		"form": form,
	}
	return render(request, 'post_create.html', context)

def post_update(request, post_slug):
	instance = get_object_or_404(Post, slug=post_slug)
	form = PostForm(request.POST or None, instance=instance)
	if form.is_valid():
		form.save()
		return redirect(instance.get_absolute_url())
	context = {
	"form": form,
	"instance": instance,
	"title": "Update",
	}
	return render(request, 'post_update.html', context)

def post_delete(request, post_slug):
	one_object = get_object_or_404(Post, slug=post_slug)
	one_object.delete()
	messages.success(request, "Successfully deleted!")
	return redirect("posts:list")

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>
	{% block title_name %}
		
	{% endblock title_name %}
	</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

<div class="container">
	{% block mainBody %}
	{% include "messages.html" %}
	
		
	{% endblock mainBody %}
</div>

	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

posts/templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

posts/templates/post_create.html
{% include "base.html" %}

{% block title_name %}
 	{{title}}
{% endblock title_name %}
 
{% block mainBody %}
	<form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Create Post">
	</form>
{% endblock mainBody %}

	

posts/templates/post_detail.html
{% include "base.html" %}

{% block title_name %}
	<div class="col-sm-6 col-sm-offset-3">
	<h2>The Post {{title}} Page</h2>
	</div>
{% endblock title_name %}

{% block mainBody %}

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		{% if object_detail.image %}
		<img src="{{object_detail.image.url}}" alt="" class="img-responsive">
		{% endif %}
		<h1>{{object_detail.title}} <small>{{object_detail.timestamp|timesince}} ago</small></h1>
		<p>{{object_detail.content|linebreaks}}</p>

		<a href="{% url 'posts:list' %}" class="btn btn-primary">Go Back to List</a>
	</div>
</div>


	
{% endblock mainBody %}

posts/templates/post_list.html
{% include "base.html" %}


{% block title_name %}
	<div class="col-sm-6 col-sm-offset-5">
		<h1>{{title}}</h1>
	</div>
{% endblock title_name %}

{% block mainBody %}

<div class="row">
{% for x in post_list  %}
	<div class="col-sm-6 col-sm-offset-3">
		<div class="thumbnail">

				{% if x.image %}
					<img src="{{x.image.url}}" alt="" class="img-responsive">
				{% endif %}
					<div class="caption">

						<h3><a href="{{x.get_absolute_url}}">{{x.title}}</a> <small>{{x.timestamp|timesince}} ago</small></h3>

						<p>{{x.content|linebreaks|truncatechars:100}}</p>

						<p><a href="{{x.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>

			</div>
		</div>
	</div>
{% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?page={{ post_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}
        </span>

        {% if post_list.has_next %}
            <a href="?page={{ post_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock mainBody %}

posts/templates/post_update.html
{% include "base.html" %}

{% block title_name %}
		<h1>The Post {{title}} Page</h1>
{% endblock title_name %}

{% block mainBody %}

	<form action="{% url 'posts:update' post_slug=instance.slug %}" method="POST">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" name="Update Post">
	</form>

{% endblock mainBody %}
	